[package]
name = "elrond-nft-simple-sc-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.elrond-nft-simple-sc]
path = ".."

[dependencies.elrond-wasm]
version = "0.27.4"

[dependencies.elrond-wasm-debug]
version = "0.27.4"
