[package]
name = "elrond-nft-simple-sc"
version = "0.0.0"
authors = [ "Ice <icegriffin1122@gmail.com>",]
edition = "2018"
publish = false

[lib]
path = "src/nft-simple-manager.rs"

[dependencies.elrond-wasm]
version = "0.27.4"

[dev-dependencies.elrond-wasm-debug]
version = "0.27.4"
